In [24]:
# 🎵 Chinook Music Store SQL Analysis

In [1]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect(r"C:\Users\user\Downloads\chinook.db")
cursor = conn.cursor()

In [ ]:
### 🎯 Query 1: Top 10 Customers by Total Spending

# This query joins the `invoices` and `customers` tables to calculate how much each customer has spent in total. 
# The result is sorted in descending order to find the top 10.

In [3]:
# TOP 10 Customers with highest total spending

query = '''SELECT customers.FirstName ||' '|| customers.LastName AS Customer, SUM(invoices.Total) AS TotalSpent
FROM invoices
JOIN customers ON invoices.CustomerId = customers.CustomerId
GROUP BY Customer
ORDER BY TotalSpent DESC
LIMIT 10;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

             Customer  TotalSpent
0         Helena Holý       49.62
1  Richard Cunningham       47.62
2          Luis Rojas       46.62
3     Ladislav Kovács       45.62
4       Hugh O'Reilly       45.62
5       Julia Barnett       43.62
6     Fynn Zimmermann       43.62
7       Frank Ralston       43.62
8      Victor Stevens       42.62
9       Astrid Gruber       42.62

In [ ]:
### 🎯 Query 2: Top 10 artists by sales

# This query joins the `invoice_items`, `tracks`, `albums` and `artists` tables to calculate total sales of each artist's tracks. 
# The result is sorted in descending order to find the top 10.

In [4]:
# Top 10 artists by sales

query = '''SELECT artists.Name AS artist,
		SUM(invoice_items.UnitPrice) AS TotalSale
FROM invoice_items
JOIN tracks ON invoice_items.TrackId = tracks.TrackId
JOIN albums ON tracks.AlbumId = albums.AlbumId
JOIN artists ON albums.ArtistId = artists.ArtistId
GROUP BY artist
ORDER BY TotalSale DESC
LIMIT 10;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

                    artist  TotalSale
0              Iron Maiden     138.60
1                       U2     105.93
2                Metallica      90.09
3             Led Zeppelin      86.13
4                     Lost      81.59
5               The Office      49.75
6  Os Paralamas Do Sucesso      44.55
7              Deep Purple      43.56
8            Faith No More      41.58
9             Eric Clapton      39.60

In [ ]:
### 🎯 Query 3: Most popular genres

# This query joins the `genres`, `tracks` and `invoice_items` tables to calculate sales count by genre. 
# The result is sorted in descending order to find the top 10.

In [5]:
# Most popular genres

query = '''SELECT genres.Name AS genre,
		COUNT(invoice_items.TrackId) AS TotalCount
FROM genres
JOIN tracks ON genres.GenreId = tracks.GenreId
JOIN invoice_items ON tracks.TrackId = invoice_items.TrackId
GROUP BY genre
ORDER BY TotalCount DESC
LIMIT 10;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

                genre  TotalCount
0                Rock         835
1               Latin         386
2               Metal         264
3  Alternative & Punk         244
4                Jazz          80
5               Blues          61
6            TV Shows          47
7            R&B/Soul          41
8           Classical          41
9              Reggae          30

In [ ]:
### 🎯 Query 4: Best-selling albums

# This query joins the `albums`, `tracks` and `invoice_items` tables to calculate total sales count for each album. 
# The result is sorted in descending order to find the top 5.

In [6]:
# Best-selling albums

query = '''SELECT albums.Title AS album,
		COUNT(invoice_items.TrackId) AS TotalCount
FROM albums
JOIN tracks ON albums.AlbumId = tracks.AlbumId
JOIN invoice_items ON tracks.TrackId = invoice_items.TrackId
GROUP BY album
ORDER BY TotalCount DESC
LIMIT 5;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

            album  TotalCount
0  Minha Historia          27
1   Greatest Hits          26
2       Unplugged          25
3        Acústico          22
4   Greatest Kiss          20

In [ ]:
### 🎯 Query 5: Top 10 countries by sales

# This query uses the `invoices` table to calculate total sales count for each country. 
# The result is sorted in descending order to find the top 10.

In [7]:
# Top 10 countries by sales

query = '''SELECT invoices.BillingCountry AS country,
		SUM(invoices.Total) AS sales
FROM invoices
GROUP BY country
ORDER BY sales DESC
LIMIT 10;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

          country   sales
0             USA  523.06
1          Canada  303.96
2          France  195.10
3          Brazil  190.10
4         Germany  156.48
5  United Kingdom  112.86
6  Czech Republic   90.24
7        Portugal   77.24
8           India   75.26
9           Chile   46.62

In [ ]:
### 🎯 Query 6: Monthly revenue trend

# This query uses the `invoices` table to calculate sales per month.

In [8]:
# Monthly revenue trend

query = '''SELECT 
	strftime('%Y-%m', invoices.InvoiceDate) AS Month,
	SUM(invoices.Total) AS MonthlyRevenue
FROM invoices
GROUP BY Month
ORDER BY Month;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

      Month  MonthlyRevenue
0   2009-01           35.64
1   2009-02           37.62
2   2009-03           37.62
3   2009-04           37.62
4   2009-05           37.62
5   2009-06           37.62
6   2009-07           37.62
7   2009-08           37.62
8   2009-09           37.62
9   2009-10           37.62
10  2009-11           37.62
11  2009-12           37.62
12  2010-01           52.62
13  2010-02           46.62
14  2010-03           44.62
15  2010-04           37.62
16  2010-05           37.62
17  2010-06           37.62
18  2010-07           37.62
19  2010-08           37.62
20  2010-09           36.63
21  2010-10           37.62
22  2010-11           37.62
23  2010-12           37.62
24  2011-01           37.62
25  2011-02           37.62
26  2011-03           37.62
27  2011-04           51.62
28  2011-05           42.62
29  2011-06           50.62
30  2011-07           37.62
31  2011-08           37.62
32  2011-09           37.62
33  2011-10           37.62
34  2011-11           23.76
35  2011-12           37.62
36  2012-01           37.62
37  2012-02           37.62
38  2012-03           37.62
39  2012-04           37.62
40  2012-05           37.62
41  2012-06           37.62
42  2012-07           39.62
43  2012-08           47.62
44  2012-09           46.71
45  2012-10           42.62
46  2012-11           37.62
47  2012-12           37.62
48  2013-01           37.62
49  2013-02           27.72
50  2013-03           37.62
51  2013-04           33.66
52  2013-05           37.62
53  2013-06           37.62
54  2013-07           37.62
55  2013-08           37.62
56  2013-09           37.62
57  2013-10           37.62
58  2013-11           49.62
59  2013-12           38.62

In [ ]:
### 🎯 Query 7: Top 5 employees by sales

# This query joins the `employees`, `customers` and `invoices` tables to calculate the total sales made by each employee. 
# The result is sorted in descending order to find the top 5.

In [9]:
# Top 5 employees by sales

query = '''SELECT employees.FirstName ||' '|| employees.LastName AS employee,
		SUM(invoices.Total) AS TotalSales
FROM employees
LEFT JOIN customers ON employees.EmployeeId = customers.SupportRepId
LEFT JOIN invoices ON customers.CustomerId = invoices.CustomerId
GROUP BY employee
ORDER BY TotalSales DESC
LIMIT 5;'''

# Fetch results

df = pd.read_sql_query(query, conn)
df

        employee  TotalSales
0   Jane Peacock      833.04
1  Margaret Park      775.40
2  Steve Johnson      720.16
3    Robert King         NaN
4  Nancy Edwards         NaN

In [10]:
conn.close()